replicaCount: 1

image:
  tag: dev

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

logLevel: DEBUG

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

service:
  type: LoadBalancer
  port: 3000

serviceAccount:
  name: nodeapp-sa
