replicaCount: 5

image:
  repository: acrdevopsdemoks.azurecr.io/nodeapp
  tag: latest
  pullPolicy: IfNotPresent


autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

logLevel: WARN

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

service:
  type: LoadBalancer
  port: 3000

serviceAccount:
  name: nodeapp-sa
