replicaCount: 3

image:
  repository: acrdevopsdemoks.azurecr.io/nodeapp
  tag: latest
  pullPolicy: IfNotPresent


autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80

logLevel: INFO

resources:
  requests:
    cpu: "300m"
    memory: "256Mi"
  limits:
    cpu: "700m"
    memory: "768Mi"

service:
  type: LoadBalancer
  port: 3000

serviceAccount:
  name: nodeapp-sa